---
Name: healthcheckprovider
---
SilverStripe\Core\Injector\Injector:
  Sunnysideup\HealthCheckProvider\Control\HealthCheckController.CustomClass:
    class: Sunnysideup\HealthCheckProvider\Control\HealthCheckController
